language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.1
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: nightly
  fast_finish: true

install:
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit